### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by ZerNox** [xoe-labs/dockery-odoo-scaffold#1]
https://xoe-labs.github.io/dockery-odoo/
First of all is the v10 supported, since im not on v11 yet.
# Make use of the provided scripts
`$ chomd -R +x ./scripts `
#Typo chmod
`git submodule add https://github.com/odoo/odoo.git vendor/odoo/cc`
Should be branched to v10 if you want to use v10 of odoo? 
Best regards 
Zernox

**Comment by blaggacao** [comment]
@ZerNox Gald to see you here, I tried yesterday to update this repo little, so that it is more likely to be testable by someone other than me :)

I have been using the v10 image for over a year now in this or similar configuration, so it should bascially work.

However, I recently updated to v11 and made some changes. There is a residual risk I might have broken something during that process for v10 and not fallen aware of.

>git submodule add https://github.com/odoo/odoo.git vendor/odoo/cc
Should be branched to v10 if you want to use v10 of odoo?

That's correct

**Comment by blaggacao** [comment]
Typo fixed here: https://github.com/xoe-labs/dockery-odoo/commit/40264e094946a3bb60f3803cfdd1c967d0dee415

By which I'm closing this. Feel free to keep asking, if you need some help or have more feedback. I'm happy to hear how things turn out in your test and provide you with fixes as things go wrong.
