### ISSUE TITLE
please don't overwrite the .bashrc

### ISSUE THREAD

**Issue by patleb** [xoe-labs/dockery-odoo-scaffold#24]
Seriously, why overwriting the [.bashrc](https://github.com/xoe-labs/dockery-odoo-scaffold/blob/81602e3cdefe41005b301c1b4d16aa83545bdbdb/hack/init_repo.py#L198)?

**Comment by blaggacao** [comment]
Thanks for reporting. Does https://github.com/xoe-labs/dockery-odoo-scaffold/commit/fe8031effabdcbc34cac150894437aa7fd1bab0f fix it? - It was probably due to an oversight of recent refactoring to python. If this solves the issue, please close.

If the question is about why using `.bashrc` at all:
- We need to maintain this external state in the environment for the compose impersonation to work.
- I did not find a way to get independent from this external state as docker does not map users, yet (it just passes them through transparently).

**Comment by patleb** [comment]
You might want to look if the line is already there before appending.

**Comment by blaggacao** [comment]
Yep, indeed. It's supposed to be implicit by the [environment check](https://github.com/xoe-labs/dockery-odoo-scaffold/blob/fe8031effabdcbc34cac150894437aa7fd1bab0f/hack/init_repo.py#L192-L193). I guess that's ok.
